# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EtecS52Y_niKXUpBhJSha29AcjCcPGmM
"""

import streamlit as st
import pickle
import matplotlib.pyplot as plt

# ================= LOAD MODEL =================
with open("insurance_model.pkl", "rb") as file:
    model = pickle.load(file)

# ================= PAGE CONFIG =================
st.set_page_config(
    page_title="AI Driven Medical Insurance Cost Prediction",
    layout="wide"
)

st.title("🤖 AI Driven Medical Insurance Cost Prediction")
st.write("Predict medical insurance charges using machine learning.")

# ================= LAYOUT =================
left_col, right_col = st.columns(2)

# ================= LEFT SIDE: INPUT =================
with left_col:
    st.subheader("🧾 Enter Customer Details")

    age = st.number_input("Age", min_value=1, max_value=100, value=30)
    bmi = st.number_input("BMI", min_value=10.0, max_value=50.0, value=25.0)
    children = st.number_input("Number of Children", min_value=0, max_value=5, value=0)

    sex = st.radio("Sex", ["female", "male"])
    smoker = st.radio("Smoker", ["no", "yes"])
    region = st.selectbox(
        "Region",
        ["southwest", "southeast", "northwest", "northeast"]
    )

    predict_btn = st.button("🔍 Calculate Insurance Cost")

# ================= ENCODING (MATCH TRAINING) =================
sex_val = 1 if sex == "male" else 0
smoker_val = 1 if smoker == "yes" else 0

region_map = {
    "southwest": 0,
    "southeast": 1,
    "northwest": 2,
    "northeast": 3
}
region_val = region_map[region]

# ================= RIGHT SIDE: OUTPUT =================
with right_col:
    st.subheader("📊 Prediction & Analysis")

    if predict_btn:
        # ---- INPUT ARRAY (EXACT SHAPE & ORDER) ----
        input_array = [
            [
                int(age),
                int(sex_val),
                float(bmi),
                int(children),
                int(smoker_val),
                int(region_val)
            ]
        ]

        # ---- PREDICTION ----
        prediction = model.predict(input_array)[0]

        st.success(f"💰 Predicted Insurance Cost: ₹ {prediction:,.2f}")

        # ================= GRAPH =================
        st.subheader("📈 BMI vs Predicted Insurance Cost")

        bmi_values = list(range(18, 41))
        cost_predictions = []

        for b in bmi_values:
            temp_input = [[
                int(age),
                int(sex_val),
                float(b),
                int(children),
                int(smoker_val),
                int(region_val)
            ]]
            cost_predictions.append(model.predict(temp_input)[0])

        fig, ax = plt.subplots()
        ax.plot(bmi_values, cost_predictions)
        ax.set_xlabel("BMI")
        ax.set_ylabel("Predicted Insurance Cost")
        ax.set_title("Impact of BMI on Insurance Cost")

        st.pyplot(fig)

    else:
        st.info("👈 Enter details on the left and click **Calculate Insurance Cost**")