# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u-1jcR3nfPQI33QkZTpRAs73gcrPYYBM
"""

import streamlit as st
import pandas as pd
import joblib

st.title("💊 Insurance Charges Prediction")

model = joblib.load("insurance_model.pkl")
cols = joblib.load("model_columns.pkl")

st.header("Enter Details")

age = st.number_input("Age", value=30)
sex = st.selectbox("Sex", ["male","female"])
bmi = st.number_input("BMI", value=25.0)
children = st.number_input("Children", value=0)
smoker = st.selectbox("Smoker", ["yes","no"])
region = st.selectbox("Region", ["southwest","southeast","northwest","northeast"])

input_df = pd.DataFrame({
    "age":[age],
    "sex":[sex],
    "bmi":[bmi],
    "children":[children],
    "smoker":[smoker],
    "region":[region]
})

input_df = pd.get_dummies(input_df)

for col in cols:
    if col not in input_df:
        input_df[col] = 0

input_df = input_df[cols]

if st.button("Predict Charges"):
    prediction = model.predict(input_df)
    st.success(f"Predicted Insurance Charges: ₹ {round(prediction[0],2)}")