# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OSFEy6RFA0Y_43-k961LV-iEbFRQDYE8
"""

import streamlit as st
import pickle
import numpy as np

# Load trained model
model = pickle.load(open("insurance_model.pkl", "rb"))

st.set_page_config(page_title="Medical Insurance Charges Prediction", layout="wide")

# MAIN HEADING
st.title("🏥 Medical Insurance Charges Prediction")

# Create left-right layout
left_col, right_col = st.columns(2)

# ---------------- LEFT SIDE (INPUTS) ----------------
with left_col:
    st.subheader("Enter Details")

    age = st.number_input("Age", min_value=1, max_value=100, value=30)
    sex = st.selectbox("Sex", ["male", "female"])
    bmi = st.number_input("BMI", min_value=10.0, max_value=50.0, value=25.0)
    children = st.number_input("Children", min_value=0, max_value=5, value=0)
    smoker = st.selectbox("Smoker", ["yes", "no"])
    region = st.selectbox("Region", ["southwest", "southeast", "northwest", "northeast"])

    predict_btn = st.button("Predict Charges")

# ---------------- RIGHT SIDE (OUTPUT) ----------------
with right_col:
    st.subheader("Entered Values Overview")

    st.write(f"**Age:** {age}")
    st.write(f"**Sex:** {sex}")
    st.write(f"**BMI:** {bmi}")
    st.write(f"**Children:** {children}")
    st.write(f"**Smoker:** {smoker}")
    st.write(f"**Region:** {region}")

    if predict_btn:
        # Encoding (must match training)
        sex_map = {"male": 0, "female": 1}
        smoker_map = {"no": 0, "yes": 1}
        region_map = {
            "southwest": 0,
            "southeast": 1,
            "northwest": 2,
            "northeast": 3
        }

        input_data = np.array([[
            age,
            sex_map[sex],
            bmi,
            children,
            smoker_map[smoker],
            region_map[region]
        ]])

        prediction = model.predict(input_data)

        st.success(f"💰 Estimated Insurance Charges: ₹ {int(prediction[0])}")