# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xWQbQov2yoxv2zDPSetN52ydQE9FdYsL
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle

# -------------------------------
# Page config
# -------------------------------
st.set_page_config(page_title="Insurance Cost Prediction", layout="centered")

st.title("💰 Insurance Cost Prediction App")
st.write("Predict medical insurance charges using Machine Learning")

# -------------------------------
# Load trained model
# -------------------------------
@st.cache_resource
def load_model():
    with open("model.pkl", "rb") as f:
        model = pickle.load(f)
    return model

model = load_model()

# -------------------------------
# User input section
# -------------------------------
st.header("Enter Customer Details")

age = st.number_input("Age", min_value=18, max_value=100, value=25)
sex = st.selectbox("Sex", ["male", "female"])
bmi = st.number_input("BMI", min_value=10.0, max_value=60.0, value=22.0)
children = st.number_input("Number of Children", min_value=0, max_value=5, value=0)
smoker = st.selectbox("Smoker", ["yes", "no"])
region = st.selectbox("Region", ["southwest", "southeast", "northwest", "northeast"])

# -------------------------------
# Encode categorical values
# -------------------------------
sex = 1 if sex == "male" else 0
smoker = 1 if smoker == "yes" else 0

region_dict = {
    "southwest": 0,
    "southeast": 1,
    "northwest": 2,
    "northeast": 3
}
region = region_dict[region]

# -------------------------------
# Prediction
# -------------------------------
if st.button("Predict Insurance Cost"):
    input_data = np.array([[age, sex, bmi, children, smoker, region]])
    prediction = model.predict(input_data)

    st.success(f"💵 Estimated Insurance Cost: ₹ {prediction[0]:,.2f}")