# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XIB7hA2J0p5Ap76AZT9joBy5wbP247HO
"""

import streamlit as st
import pandas as pd
from sklearn.linear_model import LinearRegression

st.set_page_config(page_title="Insurance Cost Prediction")

st.title("💰 Medical Insurance Cost Prediction")

# -----------------------------
# Load dataset
# -----------------------------
@st.cache_data
def load_data():
    return pd.read_csv("insurance.csv")

data = load_data()

# -----------------------------
# Preprocessing
# -----------------------------
data["sex"] = data["sex"].map({"male": 1, "female": 0})
data["smoker"] = data["smoker"].map({"yes": 1, "no": 0})
data["region"] = data["region"].map({
    "southwest": 0,
    "southeast": 1,
    "northwest": 2,
    "northeast": 3
})

X = data.drop("charges", axis=1)
y = data["charges"]

# -----------------------------
# Train model
# -----------------------------
model = LinearRegression()
model.fit(X, y)

# -----------------------------
# User inputs
# -----------------------------
st.header("Enter Details")

age = st.number_input("Age", 18, 100, 25)
sex = st.selectbox("Sex", ["male", "female"])
bmi = st.number_input("BMI", 10.0, 60.0, 22.0)
children = st.number_input("Children", 0, 5, 0)
smoker = st.selectbox("Smoker", ["yes", "no"])
region = st.selectbox("Region", ["southwest", "southeast", "northwest", "northeast"])

sex = 1 if sex == "male" else 0
smoker = 1 if smoker == "yes" else 0
region = {"southwest": 0, "southeast": 1, "northwest": 2, "northeast": 3}[region]

# -----------------------------
# Prediction
# -----------------------------
if st.button("Predict"):
    input_data = [[age, sex, bmi, children, smoker, region]]
    prediction = model.predict(input_data)
    st.success(f"💵 Estimated Insurance Cost: ₹ {prediction[0]:,.2f}")